logging:
  version: 1
  disable_existing_loggers: False

  formatters:
    simple:
      format: "%(asctime)s %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    error:
      format: "%(asctime)s %(name)s %(levelname)s %(filename)s::%(funcName)s[%(lineno)d]:%(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout

    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: wx_info.log
      maxBytes: 10485760  # 10MB
      backupCount: 20
      encoding: utf8

    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: error
      filename: wx_error.log
      maxBytes: 10485760  # 10MB
      backupCount: 20
      encoding: utf8

  root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]


bot:
  config: # -----config配置这不填-----
    callback:         # -----callback配置-----
    http_port: 9999   # http api端口
    http_host: 0.0.0.0  # http api监听地址
  managers: []  # 管理员列表，wxid，不是微信昵称
  groups:
    enable: []  # 允许响应的群 roomId，大概长这样：2xxxxxxxxx3@chatroom
  news:
    receivers: []  # 定时新闻接收人（roomid 或者 wxid）

  report_reminder:
    receivers: []  # 定时日报周报月报提醒（roomid 或者 wxid）
  bing:
    receivers: []  # 定时日报周报月报提醒（roomid 或者 wxid）


history_msg:  # 历史消息记录
  enable: True  # 是否开启历史消息记录
  group: []  # 历史消息记录群组


chatgpt:  # -----chatgpt配置这行不填-----
  # openai的key，需要自己去获取 ，地址：https://beta.openai.com/account/api-keys
  api_key:  sk-xxxxxxxxxxxxx  
  # 反代的api,默认值 https://api.openai.com (境内无法访问) , https://openai.451024.xyz (境内可访问)
  base_url:  https://api.openai.com 


sparkapi:
  #以下密钥信息从控制台获取
  #获取地址https://console.xfyun.cn/services/bm3
  appid:      #填写控制台中获取的 APPID 信息
  api_secret:   #填写控制台中获取的 APISecret 信息
  api_key:    #填写控制台中获取的 APIKey 信息

  #用于配置大模型版本，默认“general/generalv2/generalv3”
  domain:  generalv3  
  Spark_url: wss://spark-api.xf-yun.com/v3.1/chat  




gemini: # -----bard配置这行不填-----
  api_key:  # api-key 创建地址：https://ai.google.dev/pricing?hl=en，创建后复制过来即可 
  url: https://gemini.451024.xyz #base_url
  model: gemini-pro # 选择模型，可选参数：gpt2/gpt2-medium/gpt2-large/gpt2-xl/t5-small/t5-base/t5-large/t5-3b/t5-11b
